pull_request_title: Update translations via Crowdin.
pull_request_labels:
  - Translation


files:
  - source: /app/src/main/res/values/preferences.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
